### ISSUE TITLE
cana 错误，无法同步数据啊！！！！

### ISSUE THREAD

**Issue by irwinai** [alibaba/otter#115]
pid:1 nid:1 exception:canal:canal:com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error! pls check. you need (at least one of) the SUPER,REPLICATION CLIENT privilege(s) for this operation 

这是什么情况请问

**Comment by agapple** [comment]
请下看quickstart，开启binlog记录以及对指定账户授权

**Comment by dukeshiny** [comment]
@agapple 你好我的也遇到了问题：
ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.22.5.115:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error! pls check. you need (at least one of) the SUPER,REPLICATION CLIENT privilege(s) for this operation
是不是不能监控阿里云RDS上面的从库的binlog？

**Comment by waterzmh** [comment]
重启mysql
